#!/usr/bin/env python2
# Python script for get man mages for any MPI binding.
#
# Originally mostly intended for MPI C++ bindings, but also useful for
# the closely related python bindings in mpi4py, whose names can vary
# quite a bit from their C and Fortran counterparts, and also nice to
# get man pages when you don't remember or know the exact MPI routine
# name.
#
# To be ported soon to python 3
#
# Usage example: 
#    $ mpiman AllGather
#
# Notes:
#   - Search is case-insensitive.
#   - Following prefixes may be omitted:
#     "MPI::", "MPI::COMM::", "MPI::CARTCOMM::", 
#     "MPI::INTRACOMM::", "MPI::REQUEST::", 
#     "MPI::GROUP::", "MPI::STATUS", "MPI::GRAPHCOMM"
#     (this is too much, and leads to ambiguities: need a fix!)
#   - Since fortran bindings have the same name as the C ones but
#     all capitalized, so mostly they get picked up automatically.
#
# Ramses van  Zon, SciNet, UoT, 2010-2023

import os,sys

#Map missing cxx man page keys to real man page keys
#   The keys have been capitalized to do case insensitive queries. 
#   Contains fake keys 'deprecatedXX' for deprecated MPI1 fortran and c
#   bindings with no c++ equivalent. Because these keys are not
#   capitalized, they will not be found even when typing "mpiman
#   deprecated01". A bit of a hack, admittedly.
mpi_bindings ={'MPI::COMM::ABORT'                   : 'MPI_Abort',
               'MPI::COMM::ALLGATHER'               : 'MPI_Allgather',
               'MPI::COMM::ALLGATHERV'              : 'MPI_Allgatherv',
               'MPI::COMM::ALLREDUCE'               : 'MPI_Allreduce',
               'MPI::COMM::ALLTOALL'                : 'MPI_Alltoall',
               'MPI::COMM::ALLTOALLV'               : 'MPI_Alltoallv',
               'MPI::COMM::ALLTOALLW'               : 'MPI_Alltoallw',
               'MPI::COMM::BARRIER'                 : 'MPI_Barrier',
               'MPI::COMM::BCAST'                   : 'MPI_Bcast',
               'MPI::COMM::BSEND_INIT'              : 'MPI_Bsend_init',
               'MPI::COMM::BSEND'                   : 'MPI_Bsend',
               'MPI::ATTACH_BUFFER'                 : 'MPI_Buffer_attach',
               'MPI::DETACH_BUFFER'                 : 'MPI_Buffer_detach',
               'MPI::REQUEST::CANCEL'               : 'MPI_Cancel',
               'MPI::CARTCOMM::GET_COORDS'          : 'MPI_Cart_coords',
               'MPI::INTRACOMM::CREATE_CART'        : 'MPI_Cart_create',
               'MPI::CARTCOMM::GET_TOPO'            : 'MPI_Cart_get',
               'MPI::CARTCOMM::MAP'                 : 'MPI_Cart_map',
               'MPI::CARTCOMM::GET_CART_RANK'       : 'MPI_Cart_rank',
               'MPI::CARTCOMM::SHIFT'               : 'MPI_Cart_shift',
               'MPI::CARTCOMM::SUB'                 : 'MPI_Cart_sub',
               'MPI::CARTCOMM::GET_DIM'             : 'MPI_Cartdim_get',
               'MPI::COMM::CREATE_ERRHANDLER'       : 'MPI_Comm_create_errhandler',
               'MPI::COMM::CREATE_KEYVAL'           : 'MPI_Comm_create_keyval',
               'MPI::INTERCOMM::CREATE'             : 'MPI_Comm_create',         ######
               'MPI::COMM::DELETE_ATTR'             : 'MPI_Comm_delete_attr',
               'MPI::INTRACOMM::DUP'                : 'MPI_Comm_dup',
               'MPI::COMM::FREE_KEYVAL'             : 'MPI_Comm_free_keyval',
               'MPI::COMM::FREE'                    : 'MPI_Comm_free',
               'MPI::COMM:GET_ATTR'                 : 'MPI_Comm_get_attr',
               'MPI::COMM::GET_ERRHANDLER'          : 'MPI_Comm_get_errhandler',
               'MPI::COMM::GET_PARENT'              : 'MPI_Comm_get_parent',
               'MPI::COMM::GET_GROUP'               : 'MPI_Comm_group',
               'MPI::GET_RANK'                      : 'MPI_Comm_rank',
               'MPI::INTERCOMM::GET_REMOTE_GROUP'   : 'MPI_Comm_remote_group',
               'MPI::INTERCOMM::GET_REMOTE_SIZE'    : 'MPI_Comm_remote_size',
               'MPI::COMM::SET_ATTR'                : 'MPI_Comm_set_attr',
               'MPI::COMM::SET_ERRHANDLER'          : 'MPI_Comm_set_errhandler',
               'MPI::COMM::GET_SIZE'                : 'MPI_Comm_size',
               'MPI::INTERCOMM::SPLIT'              : 'MPI_Comm_split',
               'MPI::COMM::IS_INTER'                : 'MPI_Comm_test_inter',
               'MPI::COMPUTE_DIMS'                  : 'MPI_Dims_create',        ######
               'MPI::ERRHANDLER::FREE'              : 'MPI_Errhandler_free',
               'MPI::GET_ERROR_CLASS'               : 'MPI_Error_class',
               'MPI::GET_ERROR_STRING'              : 'MPI_Error_string',
               'MPI::INTRACOMM::EXSCAN'             : 'MPI_Exscan',             ######
               'MPI::IS_FINALIZED'                  : 'MPI_Finalized',
               'MPI::FINALIZE'                      : 'MPI_Finalize',
               'MPI::COMM::GATHER'                  : 'MPI_Gather',
               'MPI::GET_ADDRESS'                   : 'MPI_Get_address',
               'MPI::STATUS::GET_COUNT'             : 'MPI_Get_count',
               'MPI::STATUS::GET_ELEMENTS'          : 'MPI_Get_elements',
               'MPI::GET_PROCESSOR_NAME'            : 'MPI_Get_processor_name',
               'MPI::GET_VERSION'                   : 'MPI_Get_version',
               'MPI::INTRACOMM::CREATE_GRAPH'       : 'MPI_Graph_create',
               'MPI::GRAPHCOMM::MAP'                : 'MPI_Graph_map',
               'MPI::GRAPHCOMM::GET_NEIGHBORS_COUNT': 'MPI_Graph_neighbors_count',
               'MPI::GRAPHCOMM::GET_NEIGHBORS'      : 'MPI_Graph_neighbors',
               'MPI::GRAPHCOMM::GET_DIMS'           : 'MPI_Graphdims_get',
               'MPI::GROUP::COMPARE'                : 'MPI_Group_compare',
               'MPI::GROUP::DIFFERENCE'             : 'MPI_Group_difference',
               'MPI::GROUP::EXCL'                   : 'MPI_Group_excl',
               'MPI::GROUP::FREE'                   : 'MPI_Group_free',
               'MPI::GROUP::INCL'                   : 'MPI_Group_incl',
               'MPI::GROUP::INTERSECT'              : 'MPI_Group_intersection',
               'MPI::GROUP::RANGE_EXCL'             : 'MPI_Group_range_excl',
               'MPI::GROUP::RANGE_INCL'             : 'MPI_Group_range_incl',
               'MPI::GROUP::GET_RANK'               : 'MPI_Group_rank',
               'MPI::GROUP::GET_SIZE'               : 'MPI_Group_size',
               'MPI::GROUP::TRANSLATE_RANKS'        : 'MPI_Group_translate_ranks',
               'MPI::GROUP::UNION'                  : 'MPI_Group_union',
               'MPI::COMM::IBSEND'                  : 'MPI_Ibsend',
               'MPI::INIT'                          : 'MPI_Init',
               'MPI::INTRACOMM::CREATE_INTERCOMM'   : 'MPI_Intercomm_create',
               'MPI::INTERCOMM::MERGE'              : 'MPI_Intercomm_merge',
               'MPI::COMM::IPROBE'                  : 'MPI_Iprobe',
               'MPI::COMM::IRECV'                   : 'MPI_Irecv',
               'MPI::COMM::IRSEND'                  : 'MPI_Irsend',
               'MPI::COMM::ISEND'                   : 'MPI_Isend',
               'MPI::COMM::ISSEND'                  : 'MPI_Issend',
               'MPI::OP::INIT'                      : 'MPI_Op_create',
               'MPI::OP::FREE'                      : 'MPI_Op_free',
               'MPI::DATATYPE::PACK'                : 'MPI_Pack',
               'MPI::DATATYPE::PACK_SIZE'           : 'MPI_Pack_size',
               'MPI::PCONTROL'                      : 'MPI_Pcontrol',
               'MPI::COMM::PROBE'                   : 'MPI_Probe',
               'MPI::WIN::PUT'                      : 'MPI_Put',
               'MPI::COMM::RECV_INIT'               : 'MPI_Recv_init',
               'MPI::COMM::RECV'                    : 'MPI_Recv',
               'MPI::INTRACOMM::REDUCE'             : 'MPI_Reduce',
               'MPI::COMM::REDUCE_SCATTER'          : 'MPI_Reduce_scatter',
               'MPI::REQUEST::FREE'                 : 'MPI_Request_free',
               'MPI::COMM::RSEND_INIT'              : 'MPI_Rsend_init',
               'MPI::COMM::RSEND'                   : 'MPI_Rsend',
               'MPI::INTRACOMM::SCAN'               : 'MPI_Scan',                  #######
               'MPI::COMM::SCATTER'                 : 'MPI_Scatter',
               'MPI::COMM::SCATTERV'                : 'MPI_Scatterv',
               'MPI::COMM::SEND_INIT'               : 'MPI_Send_init',
               'MPI::COMM::SEND'                    : 'MPI_Send',
               'MPI::COMM::SENDRECV'                : 'MPI_Sendrecv',
               'MPI::COMM::SENDRECV_REPLACE'        : 'MPI_Sendrecv_replace',    ##########
               'MPI::COMM::SSEND_INIT'              : 'MPI_Ssend_init',
               'MPI::COMM::SSEND'                   : 'MPI_Ssend',
               'MPI::PREQUEST::START'               : 'MPI_Start',
               'MPI::PREQUEST::STARTALL'            : 'MPI_Startall',
               'MPI::REQUEST::TEST'                 : 'MPI_Test', 
               'MPI::REQUEST::TESTALL'              : 'MPI_Testall', 
               'MPI::REQUEST::TESTANY'              : 'MPI_Testany', 
               'MPI::REQUEST::TESTSOME'             : 'MPI_Testsome', 
               'MPI::COMM::GET_TOPOLOGY'            : 'MPI_Topo_test',          ############
               'MPI::DATATYPE::COMMIT'              : 'MPI_Type_commit',
               'MPI::DATATYPE::CREATE_CONTIGUOUS'   : 'MPI_Type_contiguous',    
               'MPI::DATATYPE::CREATE_HINDEXED'     : 'MPI_Type_create_hindexed',
               'MPI::DATATYPE::CREATE_HVECTOR'      : 'MPI_Type_create_hvector',
               'MPI::DATATYPE::CREATE_INDEXED'      : 'MPI_Type_indexed',
               'MPI::DATATYPE::CREATE_INDEXED_BLOCK': 'MPI_Type_create_indexed_block',
               'MPI::DATATYPE::CREATE_RESIZED'      : 'MPI_Type_create_resized',
               'MPI::DATATYPE::CREATE_STRUCT'       : 'MPI_Type_create_struct',
               'MPI::DATATYPE::FREE'                : 'MPI_Type_free',
               'MPI::DATATYPE::GET_TRUE_EXTENT'     : 'MPI_Type_get_true_extent',
               'MPI::DATATYPE::GET_SIZE'            : 'MPI_Type_size',
               'MPI::DATATYPE::CREATE_VECTOR'       : 'MPI_Type_vector',
               'MPI::REQUEST::WAIT'                 : 'MPI_Wait',
               'MPI::REQUEST::WAITALL'              : 'MPI_Waitall',
               'MPI::REQUEST::WAITANY'              : 'MPI_Waitany',
               'MPI::REQUEST::WAITSOME'             : 'MPI_Waitsome',
               'MPI::WTICK'                         : 'MPI_Wtick',
               'MPI::WTIME'                         : 'MPI_Wtime',
               'MPI::FILE::C2F'                     : 'MPI_File_c2f',
               'MPI::FILE::CALL_ERRHANDLER'         : 'MPI_File_call_errhandler',
               'MPI::FILE::CLOSE'                   : 'MPI_File_close',
               'MPI::FILE::CREATE_ERRHANDLER'       : 'MPI_File_create_errhandler',
               'MPI::FILE::DELETE'                  : 'MPI_File_delete',
               'MPI::FILE::F2C'                     : 'MPI_File_f2c',
               'MPI::FILE::GET_AMODE'               : 'MPI_File_get_amode',
               'MPI::FILE::GET_ATOMICITY'           : 'MPI_File_get_atomicity',
               'MPI::FILE::GET_BYTE_OFFSET'         : 'MPI_File_get_byte_offset',
               'MPI::FILE::GET_ERRHANDLER'          : 'MPI_File_get_errhandler',
               'MPI::FILE::GET_GROUP'               : 'MPI_File_get_group',
               'MPI::FILE::GET_INFO'                : 'MPI_File_get_info',
               'MPI::FILE::GET_POSITION'            : 'MPI_File_get_position',
               'MPI::FILE::GET_POSITION_SHARED'     : 'MPI_File_get_position_shared',
               'MPI::FILE::GET_SIZE'                : 'MPI_File_get_size' ,
               'MPI::FILE::GET_TYPE_EXTENT'         : 'MPI_File_get_type_extent',
               'MPI::FILE::GET_VIEW'                : 'MPI_File_get_view',
               'MPI::FILE::OPEN'                    : 'MPI_File_open',
               'MPI::FILE::IREAD'                   : 'MPI_File_iread',
               'MPI::FILE::IREAD_AT'                : 'MPI_File_iread_at',
               'MPI::FILE::IREAD_SHARED'            : 'MPI_File_iread_shared',
               'MPI::FILE::IWRITE'                  : 'MPI_File_iwrite',
               'MPI::FILE::IWRITE_AT'               : 'MPI_File_iwrite_at',
               'MPI::FILE::IWRITE_SHARED'           : 'MPI_File_iwrite_shared',
               'MPI::FILE::PREALLOCATE'             : 'MPI_File_preallocate',
               'MPI::FILE::READ'                    : 'MPI_File_read',
               'MPI::FILE::READ_ALL'                : 'MPI_File_read_all',
               'MPI::FILE::READ_ALL_BEGIN'          : 'MPI_File_read_all_begin',
               'MPI::FILE::READ_ALL_END'            : 'MPI_File_read_all_end',
               'MPI::FILE::READ_AT'                 : 'MPI_File_read_at',
               'MPI::FILE::READ_AT_ALL'             : 'MPI_File_read_at_all' ,
               'MPI::FILE::READ_AT_ALL_BEGIN'       : 'MPI_File_read_at_all_begin' ,
               'MPI::FILE::READ_AT_ALL_END'         : 'MPI_File_read_at_all_end' ,
               'MPI::FILE::READ_ORDERED'            : 'MPI_File_read_ordered' ,
               'MPI::FILE::READ_ORDERED_BEGIN'      : 'MPI_File_read_ordered_begin' ,
               'MPI::FILE::READ_ORDERED_END'        : 'MPI_File_read_ordered_end' ,
               'MPI::FILE::READ_SHARED'             : 'MPI_File_read_shared' ,
               'MPI::FILE::SEEK'                    : 'MPI_File_seek' ,
               'MPI::FILE::SEEK_SHARED'             : 'MPI_File_seek_shared' ,
               'MPI::FILE::SET_ATOMICITY'           : 'MPI_File_set_atomicity' ,
               'MPI::FILE::SET_ERRHANDLER'          : 'MPI_File_set_errhandler' ,
               'MPI::FILE::SET_INFO'                : 'MPI_File_set_info' ,
               'MPI::FILE::SET_SIZE'                : 'MPI_File_set_size' ,
               'MPI::FILE::SET_VIEW'                : 'MPI_File_set_view' ,
               'MPI::FILE::SYNC'                    : 'MPI_File_sync' ,
               'MPI::FILE::WRITE'                   : 'MPI_File_write' ,
               'MPI::FILE::WRITE_ALL'               : 'MPI_File_write_all' ,
               'MPI::FILE::WRITE_ALL_BEGIN'         : 'MPI_File_write_all_begin',
               'MPI::FILE::WRITE_ALL_END'           : 'MPI_File_write_all_end',
               'MPI::FILE::WRITE_AT'                : 'MPI_File_write_at' ,
               'MPI::FILE::WRITE_AT_ALL'            : 'MPI_File_write_at_all' ,
               'MPI::FILE::WRITE_AT_ALL_BEGIN'      : 'MPI_File_write_at_all_begin' ,
               'MPI::FILE::WRITE_AT_ALL_END'        : 'MPI_File_write_at_all_end' ,
               'MPI::FILE::WRITE_ORDERED'           : 'MPI_File_write_ordered' ,
               'MPI::FILE::WRITE_ORDERED_BEGIN'     : 'MPI_File_write_ordered_begin' ,
               'MPI::FILE::WRITE_ORDERED_END'       : 'MPI_File_write_ordered_end',
               'MPI::FILE::WRITE_SHARED'            : 'MPI_File_write_shared' ,
               # the deprecated MPI1 bindings without C++ counterpart:
               'deprecated01'                       : 'MPI_Address',
               'deprecated02'                       : 'MPI_Attr_delete',
               'deprecated03'                       : 'MPI_Attr_get',
               'deprecated04'                       : 'MPI_Attr_put',
               'deprecated05'                       : 'MPI_Errhandler_create',
               'deprecated06'                       : 'MPI_Keyval_create',
               'deprecated07'                       : 'MPI_Keyval_free',
               'deprecated08'                       : 'MPI_Type_hvector',
               'deprecated09'                       : 'MPI_Type_hindexed',
               'deprecated10'                       : 'MPI_Type_extent',
               'deprecated11'                       : 'MPI_Type_lb',
               'deprecated12'                       : 'MPI_Type_ub',
               'deprecated13'                       : 'MPI_Type_struct'
               }

#Function to try and match a key to a man page for one argument
def find(arg):
    upcasearg=arg.upper()
    # Prefixes that may be omitted (leads to undetected ambiguities: need to return a list, but not yet implemented)
    prefixes = "", "MPI::", "MPI::COMM::", "MPI::CARTCOMM::", "MPI::INTERCOMM::", "MPI::INTRACOMM::", "MPI::REQUEST::", "MPI::GROUP::", "MPI::STATUS", "MPI::GRAPHCOMM", "MPI::FILE::"
    # Check the keys first
    for prefix in prefixes:
        try:
            return mpi_bindings[prefix+upcasearg]
        except KeyError: pass #if not found, keep looking with other prefix
    prefixes = "", "MPI_", "MPI_ATTR_", "MPI_CART_", "MPI_GROUP_", "MPI_REQUEST_"
    #  Check the values if nothing was found 
    for prefix in prefixes:
        for lang in mpi_bindings.values(): 
            if prefix+upcasearg == lang.upper():
                return lang
    return ""
 
#Function to try and find a man page for one argument
def mpiman(key):
    realkey = find(key)
    if realkey == "":
        print key + " not in mpi manpage list."
    else:
        os.system("man " + realkey)
 
#Program starts here: Loops over all arguments (except the first, which is mpiman itself)
if (len(sys.argv) == 1):
    print "a list of c++ bindings:"
    for all in sorted(mpi_bindings.keys()):
        if all.startswith("MPI::"):
            print all
else:
    for arg in sys.argv[1:]:
        mpiman(arg)

#end of python program
